 ##################eureka config######################################
server:
  port: 8001

spring:
  application:
    name: eureka-client-consumer

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 15
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://1dd2ccb4-98b3-4f4d-a961-3187d82176dd.nacos.cn-north-4.cse.myhuaweicloud.com:8848/nacos/eureka}
  ##################eureka config##############################################