server:
  port: 8003

spring:
  application:
    name: providerA
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: providerA
        heartbeat:
          enabled: true
        instanceZone: A
        catalog-services-watch:
          enabled: false