server:
  port: 8001

spring:
  application:
    name: consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: consumer
        heartbeat:
          enabled: true
        instanceZone: A
        catalog-services-watch:
          enabled: false