
server:
  port: 9092

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


current:
  engine: CSE


#spring:
#  application:
#    name: nacos-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://127.0.0.1:8848
#      config:
#        server-addr: http://127.0.0.1:8848