server:
  port: 8004

spring:
  application:
    name: providerB
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: providerB
        heartbeat:
          enabled: true
        instanceZone: A
        catalog-services-watch:
          enabled: false