##################eureka test######################
spring:
  application:
    name: eureka-client-provider

server:
  port: 8002

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
#############################################################